### ISSUE TITLE
NoMethodError - undefined method `generic_subscription' for nil:NilClass

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-pro/bullet_train-billing-stripe#11]
```
NoMethodError: undefined method `generic_subscription' for nil:NilClass (NoMethodError)

        topic.generic_subscription.update(status: status)
             ^^^^^^^^^^^^^^^^^^^^^
  from bullet_train-billing-stripe (1.0.1) app/models/webhooks/incoming/stripe_webhook.rb:36:in `process'
  from bullet_train-incoming_webhooks (1.2.22) app/models/webhooks/incoming/webhook.rb:28:in `verify_and_process'
  from bullet_train-incoming_webhooks (1.2.22) app/jobs/webhooks/incoming/webhook_processing_job.rb:5:in `perform'
```

It seems like this happened when the BT app received a webhook for a subscription that maybe hadn't yet been committed to the database. When I pull up the webhook record mentioned in the error report it points to a topic_id of `sub_xxx` and there is a `Billing::Stripe::Subscription` in the database with that ID, which is what makes me think this is a timing problem of some sort.

**Comment by jagthedrummer** [comment]
This is still happening every now and then. It seems like most of them are timing issues because there will be just one failure. And then when I go to investigate the stored webhook it has a `topic` and a `topic.generic_subscription`.
